apiVersion: v1
kind: Pod
metadata:
  name: vote
  labels:
    name: vote-pod
    app: voting-app
spec:
  containers:
    - name: vote
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80