apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    name: vote-deployment
    app: voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: vote-pod
      app: voting-app
  template:
    metadata:
      name: vote
      labels:
        name: vote-pod
        app: voting-app
    spec:
      containers:
        - name: vote
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
    